version: '3.8'
services:
  codecept:
    build: ./docker/codecept/
    depends_on:
      - web
    volumes:
      - .:/project
    command: "run"
  web:
    build: ./docker/php/
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
